### ISSUE TITLE
程序错误啊

### ISSUE THREAD

**Issue by nmweizi** [ipconfiger/simpleweixin#1]
一个是例子中的settings.token
一个是check_signature中的"".join([token, timestamp,nonce]，反了。

**Comment by plutoid** [comment]
作者估计是写里关键的几个方法，我现在也调不通。但思路应该没有大问题。比如

```
reply.update(callback(params['MsgType'],params))
```

期待作者有时间时更新下。

**Comment by ipconfiger** [comment]
抱歉，最近比较忙，下周会抽时间fix这些bug

**Comment by ipconfiger** [comment]
经过核查发现SDK本身问题不大，主要是例子里有bug，回头再来修改例子
